# Generated by Django 4.0.2 on 2022-02-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_recipe_recipe_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish',
            field=models.CharField(choices=[('SD', 'Salad'), ('MN', 'Main'), ('SP', 'Soup'), ('DT', 'Dessert'), ('DK', 'Drink')], default='DT', max_length=2),
        ),
    ]
