# Generated by Django 4.0.2 on 2022-02-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dish',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('SD', 'Salad'), ('DG', 'Dressing'), ('MN', 'Main'), ('SP', 'Soup'), ('DT', 'Dessert'), ('DK', 'Drink')], default='DT', max_length=2),
        ),
    ]
